### ISSUE TITLE
The version of Java (1.8.0_221) you have used to run this analysis is deprecated 

### ISSUE THREAD

**Issue by pieterh** [ceddlyburge/sonarqube-nemo-on-appveyor#5]
The error below is shown when following the steps in the blog (https://www.appveyor.com/blog/2016/12/23/sonarqube/). I was using image Visual Studio 2019 that includes Java 11.
Adding the following two lines at the beginning of the build_script in the appveyor.yml, fixes this problem and works again as expected.
  
 - set JAVA_HOME=C:\Program Files\Java\jdk11
 - set PATH=%JAVA_HOME%\bin;%PATH%

The error that was shown before:
INFO: ------------------------------------------------------------------------
The version of Java (1.8.0_221) you have used to run this analysis is deprecated and we stopped accepting it for newly created projects. 
You can find more information here: https://sonarcloud.io/documentation/upcoming/
ERROR: 
The SonarScanner did not complete successfully
11:36:57.06  Post-processing failed. Exit code: 1

**Comment by ceddlyburge** [comment]
Thanks Pieter, I'll update the blog post.

Cheers, Cedd

**Comment by ceddlyburge** [comment]
A [PR with this change](https://github.com/appveyor/website/pull/782) is now with Appveyor
